(6-5)上級 ページング ページングを実装
horioka-organization/ex-emp-management-bugfix pull request #40
Opened 2023-06-12 07:45 UTC by mh214

レビューよろしくお願いいたします。

2023-06-12 07:50 UTC, mh214 commented
結局、グエンさんに教えてもらったjQueryので実装しました。

2023-06-12 08:11 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-06-12 08:11 UTC, igamasayuki commented on src/main/resources/templates/employee/list.html
> +    <script src="/js/pagenation.js"></script>
リンク式を使いましょう。

2023-06-12 08:11 UTC, igamasayuki commented on src/main/resources/templates/employee/list.html
> +    <script src="/js/bootstrap.min.js"></script>
リンク式を使いましょう。

2023-06-13 00:19 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2023-06-13 00:19 UTC, merged